image: node:11.13.0-alpine

pipelines:
  branches:
    master:
      - step:
          name: Build and package
          deployment: dev
          caches:
            - node
          script:
            - apk add openjdk8
            - ./gradlew build
            - npm install -g serverless
            - serverless config credentials --stage dev --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - serverless deploy --stage dev